{{- if .Values.podDisruptionBudget.enabled }}

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: {{ include "myapp.fullname" . }}

  labels:
    {{- include "myapp.labels" . | nindent 4 }}

spec:

  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}

  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}

{{- end }}
