apiVersion: v1
kind: Secret

metadata:
  name: {{ include "myapp.fullname" . }}

type: Opaque

stringData:

  USERNAME: {{ .Values.secret.USERNAME | quote }}

  PASSWORD: {{ .Values.secret.PASSWORD | quote }}
