apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: myapp
  namespace: qa

spec:
  project: default

  source:
    repoURL: https://github.com/roshikhosla04/gitops-demo.git
    targetRevision: main
    path: charts/myapp

    helm:
      valueFiles:
        - ../../environments/qa/myapp-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
